apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-microservice
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank-ms
        image: aline-bank-microservice:latest     
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8083
        envFrom:
        - secretRef:
            name: microservices-secret 
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30004
    port: 8083
    targetPort: 8083