version: "3"
services:
  account:
    container_name: account
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/aline-account-microservice:latest
    ports:
      - "8072:8072"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ENCRYPT_SECRET_KEY=${ENCRYPT_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY} 