apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account
  ports:
  - protocol: TCP
    port: 8072
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account-ms
          image: 047032559530.dkr.ecr.us-east-1.amazonaws.com/aline-account-microservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8072
          envFrom:
          - secretRef:
              name: microservices-secret