apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank
  ports:
  - protocol: TCP
    port: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-microservice
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank-ms
        image: 047032559530.dkr.ecr.us-east-1.amazonaws.com/aline-bank-microservice:latest     
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8083
        envFrom:
        - secretRef:
            name: microservices-secret
        # env:
        #   - name: APP_SERVICE_HOST
        #     value: ${APP_SERVICE_HOST}
        #   - name: AWS_ACCOUNT_ID
        #     value: ${AWS_ACCOUNT_ID}
        #   - name: AWS_DEFAULT_REGION
        #     value: ${AWS_DEFAULT_REGION}
        #   - name: DB_HOST
        #     value: ${DB_HOST}
        #   - name: DB_NAME
        #     value: ${DB_NAME}
        #   - name: DB_PASSWORD
        #     value: ${DB_PASSWORD}
        #   - name: DB_PORT
        #     value: ${DB_PORT}
        #   - name: DB_USERNAME
        #     value: ${DB_USERNAME}
        #   - name: ENCRYPT_SECRET_KEY
        #     value: ${ENCRYPT_SECRET_KEY}
        #   - name: JWT_SECRET_KEY
        #     value: "9ef2c67e-a4e2-4e32-b2dd-27b3ed641ac0"
          # - name: APP_SERVICE_HOST
          #   value: "localhost"
          # - name: AWS_ACCOUNT_ID
          #   value: "047032559530"
          # - name: AWS_DEFAULT_REGION
          #   value: "us-east-1"
          # - name: DB_HOST
          #   value: $(DB_HOST)
          # - name: "database-hl3.cxddvnyb1guo.us-east-1.rds.amazonaws.com"
          #   value: "alinedb"
          # - name: DB_PASSWORD
          #   value: "Half-Life-3"
          # - name: DB_PORT
          #   value: "3306"
          # - name: DB_USERNAME
          #   value: "hl3"
          # - name: ENCRYPT_SECRET_KEY
          #   value: "V2OHkvQj9FKEgrTWJRZVRoV21acTM="
          # - name: JWT_SECRET_KEY
          #   value: "9ef2c67e-a4e2-4e32-b2dd-27b3ed641ac0"
        resources: {}
status: {}