apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
type: 0paque
data:
  APP_SERVICE_HOST: bG9jYWxob3N0
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_HOST: Y2Fwc3RvbmVkYi5jNGxqbDZjaXNycjMudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_PORT: MzMwNg==
  DB_NAME: YWxpbmVkYg==
  AWS_ACCOUNT_ID: MDQ3MDMyNTU5NTMw
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  ENCRYPT_SECRET_KEY: UGRTZ1ZrWHAyczV2OHkvQj9FKEgrTWJRZVRoV21acTM=
  JWT_SECRET_KEY: OWVmMmM2N2UtYTRlMi00ZTMyLWIyZGQtMjdiM2VkNjQxYWMw
