apiVersion: v1
kind: Service
metadata:
  name: underwriter-service
spec:
  selector:
    app: underwriter
  ports:
  - protocol: TCP
    port: 8071
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter
  labels:
    app: underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter
  template:
    metadata:
      labels:
        app: underwriter
    spec:
      containers:
        - name: underwriter-ms
          image: 047032559530.dkr.ecr.us-east-1.amazonaws.com/aline-underwriter-microservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8071
          envFrom:
          - secretRef:
              name: microservices-secret
