apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-ms
          image: 047032559530.dkr.ecr.us-east-1.amazonaws.com/aline-user-microservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          envFrom:
          - secretRef:
              name: microservices-secret
          # env:
          #   - name: APP_SERVICE_HOST
          #     value: ${APP_SERVICE_HOST}
          #   - name: AWS_ACCOUNT_ID
          #     value: ${AWS_ACCOUNT_ID}
          #   - name: AWS_DEFAULT_REGION
          #     value: ${AWS_DEFAULT_REGION}
          #   - name: DB_HOST
          #     value: ${DB_HOST}
          #   - name: DB_NAME
          #     value: ${DB_NAME}
          #   - name: DB_PASSWORD
          #     value: ${DB_PASSWORD}
          #   - name: DB_PORT
          #     value: ${DB_PORT}
          #   - name: DB_USERNAME
          #     value: ${DB_USERNAME}
          #   - name: ENCRYPT_SECRET_KEY
          #     value: "V2OHkvQj9FKEgrTWJRZVRoV21acTM="
          #   - name: JWT_SECRET_KEY
          #     value: "9ef2c67e-a4e2-4e32-b2dd-27b3ed641ac0"






