name: test-actions
on: 
  push:
    branches:
      - feature-HL3-48
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_OUTPUT_FILE: ${{secrets.AWS_OUTPUT_TYPE}}
jobs:
  deploy-cloud-formation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install --update

      # # - uses: actions/checkout@v3
      # # - run: aws configure
      # # - run: echo "$AWS_ACCESS_KEY_ID"; echo "$AWS_SECRET_ACCESS_KEY"; echo "$AWS_DEFAULT_REGION"; echo "yaml"
      # #- run: sh aws_login.sh
      - run: pwd
      - run: ls -a
      - run: cd /home/runner/work/devops-mk/devops-mk/cloud-formation; aws cloudformation create-stack  --stack-name cloud-formation-template-stack --template-body file://full-stack.yaml
      - run: echo $?
