name: test-actions
on: 
  push:
    branches:
      - feature-HL3-48
# env:
#   AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#   AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#   AWS_DEFAULT_REGION:
#   AWS_OUTPUT_FILE: yaml
# aws configure
# echo ${AWS_ACCESS_KEY_ID}
# echo ${AWS_SECRET_ACCESS_KEY}
# echo ${AWS_DEFAULT_REGION}
# echo 'yaml'


jobs:
  deploy-cloud-formation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh .aws_login.sh
      - run: cd ../../cloudformation; aws cloudformation create-stack  --stack-name cloud-formation-template-stack --template-body file://full-stack.yaml
      - run: echo $?