name: test-actions
on: 
  push:
    branches:
      - feature-HL3-48
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_OUTPUT_FILE: ${{secrets.AWS_OUTPUT_TYPE}}
# aws configure
# echo ${AWS_ACCESS_KEY_ID}
# echo ${AWS_SECRET_ACCESS_KEY}
# echo ${AWS_DEFAULT_REGION}
# echo 'yaml'


jobs:
  deploy-cloud-formation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: aws configure
      - run: echo "$AWS_ACCESS_KEY_ID"; echo "$AWS_SECRET_ACCESS_KEY"; echo "$AWS_DEFAULT_REGION"; echo "yaml"
      #- run: sh aws_login.sh
      - run: cd ../../cloudformation; aws cloudformation create-stack  --stack-name cloud-formation-template-stack --template-body file://full-stack.yaml
      - run: echo $?